// This file is auto-generated by Payload CMS
// Run `npm run generate:types` to regenerate

export interface Weekly {
  id: string
  title: string
  slug: string
  excerpt: string
  content: unknown
  thumbnail?: string | Media | null
  tag?: 'ai-weekly' | 'tech' | 'tutorial' | null
  tagColor?: 'pink' | 'orange' | 'green' | 'blue' | 'purple' | 'yellow' | null
  publishedAt: string
  readTime?: string | null
  status?: 'draft' | 'review' | 'published' | null
  personalInsight?: unknown
  createdAt: string
  updatedAt: string
}

export interface Media {
  id: string
  alt: string
  url?: string | null
  filename?: string | null
  mimeType?: string | null
  filesize?: number | null
  width?: number | null
  height?: number | null
  createdAt: string
  updatedAt: string
}

export interface User {
  id: string
  email: string
  name?: string | null
  createdAt: string
  updatedAt: string
}

export interface SiteConfig {
  id: string
  name: string
  bio?: string | null
  avatar?: string | Media | null
  location?: string | null
  work?: string | null
  social?: {
    threads?: string | null
    github?: string | null
    linkedin?: string | null
    instagram?: string | null
  }
}
